services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ default AMQP port
      - "8080:15672"   # RabbitMQ management plugin web UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge
